CheckoutTestSln/PaymentGateway.Web/Controllers/LoginController.cs
using PaymentGateway.ServiceInterfacesModels.Interfaces;
using PaymentGateway.ServiceInterfacesModels.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;

namespace PaymentGateway.Web.Controllers
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class LoginController : Controller
    {
        private readonly IUserRepo _userRepo;

        public LoginController(IUserRepo userRepo)
        {
            _userRepo = userRepo;
        }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginUser(UserLogin userLogin)
        {
            var userLogged = _userRepo.Login(userLogin.UserName, userLogin.Password);
            if (userLogged == null)
            {
                return RedirectToAction("Index");
            }
            var userSession = new UserSession { Id = userLogged.Id, UserName = userLogged.UserName };
            Session["UserSession"] = userSession;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterUser(UserLogin user)
        {
            //Register User
            var userLogged = _userRepo.AddUser(user);

            if (userLogged.Status)
            {
                // login using new user
                var userSession = new UserSession { Id = userLogged.UserLogged.Id, UserName = userLogged.UserLogged.UserName };
                Session["UserSession"] = userSession;

            }

            // redirect to Home
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LoginPurchase(double amount, string currency, string merchantid)
        {
            PurchaseModel purchaseInfo = new PurchaseModel { amount = amount, currency = currency, MerchantId = Guid.Parse(merchantid) };
            Session["purchaseInfo"] = purchaseInfo;

            return View("Index");
        }

        public ActionResult LogOut()
        {
            Session["UserSession"] = null;
            return RedirectToAction("Index");


        }

    }
}

CheckoutTestSln/PaymentGateway.Web/Controllers/UserDetailsController.cs
using PaymentGateway.ServiceInterfacesModels.Interfaces;
using PaymentGateway.ServiceInterfacesModels.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaymentGateway.Web.Controllers
{
    public class UserDetailsController : BaseController
    {
        private readonly IUserDetails _userDetailsService;

        public UserDetailsController(IUserDetails userDetailsService)
        {
            _userDetailsService = userDetailsService;
        }

        // GET: UserDetails
        public ActionResult Index()
        {
            var model = _userDetailsService.GetUsersDetailsByUserId(UserSession.Id);
            return View(model);
        }

        // GET: UserDetails/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _userDetailsService.GetUsersDetailsById(id);
            return View(model);
        }

        // GET: UserDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDetails/Create
        [HttpPost]
        public ActionResult Create(UserDetails collection)
        {
            try
            {
                collection.UserId = UserSession.Id;
                // TODO: Add insert logic here
                var result = _userDetailsService.AddUserDetails(collection);
                if (result)
                    return RedirectToAction("Index");
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: UserDetails/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _userDetailsService.GetUsersDetailsById(id);
            return View(model);
        }

        // POST: UserDetails/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, UserDetails collection)
        {
            try
            {
                // TODO: Add update logic here
                var result = _userDetailsService.ModifyUserDetails(collection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserDetails/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _userDetailsService.GetUsersDetailsById(id);
            return View();
        }

        // POST: UserDetails/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, UserDetails collection)
        {
            try
            {
                // TODO: Add delete logic here
                var result = _userDetailsService.DeleteUserDetails(collection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CheckoutTestSln/PaymentGateway.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Payment Gateway", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("My Cards", "Index", "UserDetails", new { area = "" }, null)</li>
                    @if (Session["UserSession"] != null)
                    {
                        <li>@Html.ActionLink("Log Out", "LogOut", "Login", new { area = "" }, null)</li>

                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>