CheckoutTestSln/PaymentGateway.Web/Controllers/HomeController.cs
using PaymentGateway.ServiceInterfacesModels.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaymentGateway.Web.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IUserDetails _userDetailsService;

        public HomeController(IUserDetails userDetailsService)
        {
            _userDetailsService = userDetailsService;
        }
   
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            var model = _userDetailsService.GetUsersDetailsByUserId(UserSession.Id);
            return View(model);
        }
    }
}

CheckoutTestSln/PaymentGateway.Web/Controllers/PaymentProcessingController.cs
using PaymentGateway.ServiceInterfacesModels.Interfaces;
using PaymentGateway.ServiceInterfacesModels.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PaymentGateway.Web.Controllers
{
    public class PaymentProcessingController : BaseController
    {
        readonly IUserDetails _userDetails;
        readonly ITransaction _transactionService;

        public PaymentProcessingController(IUserDetails userDetails, ITransaction transaction)
        {
            _userDetails = userDetails;
            _transactionService = transaction;
        }

        // GET: PaymentProcessing
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult ProceedToPayment(Guid id)
        {
            var result = "Process Failed";
            var clientCardIdChosen = id;
            // Purchase model
            var purchaseModel = (PurchaseModel)Session["purchaseInfo"];
            
            // get customer details
            var customerDetails = _userDetails.GetUsersDetailsById(clientCardIdChosen);

            var deductionBody = new RequestBody
            {
                cardNumber =customerDetails.CardNumber,
                ccv =customerDetails.Ccv.Value,
                amount = purchaseModel.amount,
                expiryDate =customerDetails.ExpiryDate.Value
            };
            //process deduction customer
            var deduction = TaskDeductClient(deductionBody);
            if (deduction.Status)
            {
                // get merchant details 
                var merchantDetails = _userDetails.GetMainUsersDetailsByUserId(purchaseModel.MerchantId);

                var depositBody = new RequestBody
                {
                    cardNumber = merchantDetails.CardNumber,
                    ccv = merchantDetails.Ccv.Value,
                    amount = purchaseModel.amount,
                    expiryDate = merchantDetails.ExpiryDate.Value
                };
                // process addition of money merchant 
                var addition = TaskAdditionMerchant(depositBody);

                if (addition.Status && deduction.Status)
                {
                    //add transaction details to Db 
                    var transaction = new TransactionModel
                    {
                        UserId = UserSession.Id,
                        MerchantId = purchaseModel.MerchantId,
                        Amount = purchaseModel.amount,
                        currency = purchaseModel.currency,
                        datetimeCreated = DateTime.Now,

                        BankCreditId = addition.Id,
                        BankDebitId = deduction.Id,

                        CustomerDetailId = customerDetails.Id,
                        MerchantDetailId=merchantDetails.Id

                    };
                    _transactionService.AddTransaction(transaction);
                    result = "Process Completed Successfull ";
                }
                else { result = "Deduction was successfull but not deposit"; }
            }
            ViewBag.result = result;
            Session["purchaseInfo"] = null;
            return View();
        }

        public ApiResponseModel TaskDeductClient(RequestBody requestBody)
        {
            ApiResponseModel apiResponse = new ApiResponseModel();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:56834/api/");
                //HTTP GET
                var responseTask = client.PostAsJsonAsync("BankDeduction",requestBody);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ApiResponseModel>();
                    readTask.Wait();

                    apiResponse = readTask.Result;

                }
                else //web api sent error response 
                {
                    //log response status here..

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return apiResponse;

        }

        public ApiResponseModel TaskAdditionMerchant(RequestBody requestBody)
        {
            ApiResponseModel apiResponse = new ApiResponseModel();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:56834/api/");
                //HTTP GET
                var responseTask = client.PostAsJsonAsync("BankDeposits",requestBody);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ApiResponseModel>();
                    readTask.Wait();

                    apiResponse = readTask.Result;

                }
                else //web api sent error response 
                {
                    //log response status here..

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return apiResponse;

        }
    }
}

CheckoutTestSln/PaymentGateway.Web/Controllers/TrasactionListController.cs
using PaymentGateway.ServiceInterfacesModels.Interfaces;
using System;
using System.Web.Mvc;

namespace PaymentGateway.Web.Controllers
{
    public class TrasactionListController : BaseController
    {
        private readonly IUserDetails _userDetails;
        readonly ITransaction _transactionService;

        public TrasactionListController(IUserDetails userDetails, ITransaction transaction)
        {
            _userDetails = userDetails;
            _transactionService = transaction;
        }
       
        public ActionResult Index()
        {
            var result = _transactionService.GetAllMyTransactions(UserSession.Id);
            return View(result);
        }

    }
}

CheckoutTestSln/PaymentGateway.Web/Views/Home/Index.cshtml
@model IEnumerable<PaymentGateway.ServiceInterfacesModels.Models.UserDetails>
@using PaymentGateway.ServiceInterfacesModels.Models;
<div class="jumbotron">
    <h1>Payment Gateway</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>

</div>
<div class="row">
    @if (Session["purchaseInfo"] == null)
    {
    <div class="col-md-4">
        @Html.ActionLink("View Transactions list", "Index", "TrasactionList", new { }, new { @class = "btn btn-link" })
    </div>
    

    }
    else
    {
        
        var purchase = (PurchaseModel)Session["purchaseInfo"];
        <div>
            <h3>Item Purchased</h3>
            <br />
            Price = @purchase.amount &nbsp; @purchase.currency
            <br />

        </div>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CardNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ccv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpiryDate)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.CardNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ccv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpiryDate)
                    </td>
                    <td>
                        @Html.ActionLink("Proceed", "ProceedToPayment", "PaymentProcessing", new { id = item.Id }, new { @class = "btn btn-link" })
                    </td>
                </tr>
            }

        </table>
    }
</div>